### ISSUE TITLE
Not Bug | Feature Request

### ISSUE THREAD

**Issue by v6r** [vmthread/Spotify-Account-Generator#1]
Would it possible for you to make an Spotify Follow Tool to follow a account with the generated Accounts from this Tool?

**Comment by vmthread** [comment]
> 
> 
> Would it possible for you to make an Spotify Follow Tool to follow a account with the generated Accounts from this Tool?

I made this alr hit me ur discord Please

**Comment by v6r** [comment]
P4N7H3R#8967

**Comment by vmthread** [comment]
![image](https://user-images.githubusercontent.com/90005223/133937876-395c1168-58a0-4551-967d-2e7c430afe58.png)

**Comment by vmthread** [comment]
vmthread#4292
